// Define your categories
export const CATEGORIES = {
  1: 'Elections',
  2: 'Geopolitics & World Affairs',
  3: 'Economy & Economic Indicators',
  4: 'Financial Markets',
  5: 'Cryptocurrency',
  6: 'Science & Technology',
  7: 'Business & Corporate',
  8: 'Sports',
  9: 'Culture & Entertainment',
  10: 'Climate & Environment',
};

type CategoryId = keyof typeof CATEGORIES;

// Keyword mapping with priorities (higher number = more important)
const keywordMap: Map<string, { categoryId: CategoryId; priority: number }> = new Map([
  // High Priority (Specific Identifiers)
  ['sports', { categoryId: 8, priority: 10 }],
  ['formula 1', { categoryId: 8, priority: 10 }],
  ['f1', { categoryId: 8, priority: 10 }],
  ['mlb', { categoryId: 8, priority: 10 }],
  ['nfl', { categoryId: 8, priority: 10 }],
  ['soccer', { categoryId: 8, priority: 10 }],
  ['baseball', { categoryId: 8, priority: 10 }],
  ['crypto', { categoryId: 5, priority: 10 }],
  ['bitcoin', { categoryId: 5, priority: 10 }],
  ['btc', { categoryId: 5, priority: 10 }],
  ['ethereum', { categoryId: 5, priority: 10 }],
  ['eth', { categoryId: 5, priority: 10 }],
  ['doge', { categoryId: 5, priority: 10 }],
  ['ai', { categoryId: 6, priority: 9 }],
  ['openai', { categoryId: 6, priority: 9 }],
  ['sam altman', { categoryId: 6, priority: 9 }],
  ['deepseek', { categoryId: 6, priority: 9 }],
  ['grok', { categoryId: 6, priority: 9 }],
  ['fed', { categoryId: 3, priority: 8 }],
  ['jerome powell', { categoryId: 3, priority: 8 }],
  ['powell', { categoryId: 3, priority: 8 }],
  ['mayor', { categoryId: 1, priority: 8 }],
  ['nyc', { categoryId: 1, priority: 8 }],
  ['movies', { categoryId: 9, priority: 8 }],
  ['box office', { categoryId: 9, priority: 8 }],
  ['hollywood', { categoryId: 9, priority: 8 }],
  ['climate', { categoryId: 10, priority: 8 }],
  ['weather', { categoryId: 10, priority: 8 }],
  ['global warming', { categoryId: 10, priority: 8 }],
  ['ukraine', { categoryId: 2, priority: 8 }],
  ['putin', { categoryId: 2, priority: 8 }],
  ['russia', { categoryId: 2, priority: 8 }],
  ['zelensky', { categoryId: 2, priority: 8 }],
  ['iran', { categoryId: 2, priority: 8 }],
  ['israel', { categoryId: 2, priority: 8 }],
  ['khamenei', { categoryId: 2, priority: 8 }],
  ['middle east', { categoryId: 2, priority: 8 }],
  ['china', { categoryId: 2, priority: 8 }],
  ['taiwan', { categoryId: 2, priority: 8 }],
  ['gaza', { categoryId: 2, priority: 8 }],
  ['saudi arabia', { categoryId: 2, priority: 8 }],
  ['kupyansk', { categoryId: 2, priority: 8 }],
  ['atomic', { categoryId: 2, priority: 8 }],
  ['bomb', { categoryId: 2, priority: 8 }],
  ['nuclear', { categoryId: 2, priority: 8 }],
  ['trump', { categoryId: 1, priority: 8 }],
  ['maga', { categoryId: 1, priority: 8 }],
  ['trump presidency', { categoryId: 1, priority: 8 }],
  ['u.s. politics', { categoryId: 1, priority: 8 }],
  ['congress', { categoryId: 1, priority: 8 }],
  ['house', { categoryId: 1, priority: 8 }],
  ['immigration', { categoryId: 1, priority: 8 }],
  ['immigration/border', { categoryId: 1, priority: 8 }],
  ['cabinet', { categoryId: 1, priority: 8 }],
  ['epstein', { categoryId: 1, priority: 8 }],
  ['trump vs elon', { categoryId: 1, priority: 8 }],
  ['robert f. kennedy jr.', { categoryId: 1, priority: 8 }],
  ['elon musk', { categoryId: 1, priority: 8 }],
  ['world elections', { categoryId: 1, priority: 8 }],
  ['global elections', { categoryId: 1, priority: 8 }],
  ['elections', { categoryId: 1, priority: 8 }],
  ['dutch', { categoryId: 1, priority: 8 }],
  ['netherlands', { categoryId: 1, priority: 8 }],
  ['chile', { categoryId: 1, priority: 8 }],
  ['ireland', { categoryId: 1, priority: 8 }],
  ['romania', { categoryId: 1, priority: 8 }],
  ['south korea', { categoryId: 1, priority: 8 }],
  ['javier milei', { categoryId: 1, priority: 8 }],
  ['yoon', { categoryId: 1, priority: 8 }],
  ['czechia', { categoryId: 1, priority: 8 }],
  ['denmark', { categoryId: 2, priority: 7 }],
  ['greenland', { categoryId: 2, priority: 7 }],
  ['foreign policy', { categoryId: 2, priority: 7 }],
  ['geopolitics', { categoryId: 2, priority: 7 }],
  ['world', { categoryId: 2, priority: 7 }],
  ['world affairs', { categoryId: 2, priority: 7 }],
  ['us-iran', { categoryId: 2, priority: 7 }],
  ['economic policy', { categoryId: 3, priority: 7 }],
  ['economy', { categoryId: 3, priority: 7 }],
  ['fed rates', { categoryId: 3, priority: 7 }],
  ['macro graph', { categoryId: 3, priority: 7 }],
  ['xtrd-1', { categoryId: 3, priority: 7 }],
  ['trade war', { categoryId: 3, priority: 7 }],
  ['treasuries', { categoryId: 3, priority: 7 }],
  ['balance', { categoryId: 3, priority: 7 }],
  ['budget', { categoryId: 3, priority: 7 }],
  ['deficit', { categoryId: 3, priority: 7 }],
  ['funding', { categoryId: 3, priority: 7 }],
  ['business', { categoryId: 7, priority: 6 }],
  ['big tech', { categoryId: 7, priority: 6 }],
  ['crypto prices', { categoryId: 5, priority: 6 }],
  ['hit price', { categoryId: 5, priority: 6 }],
  ['monthly', { categoryId: 5, priority: 6 }],
  ['crypto policy', { categoryId: 5, priority: 6 }],
  ['crypto summit', { categoryId: 5, priority: 6 }],
  ['airdrops', { categoryId: 5, priority: 6 }],
  ['pre-market', { categoryId: 5, priority: 6 }],
  ['finance', { categoryId: 4, priority: 6 }],
  ['tech', { categoryId: 6, priority: 6 }],
  ['top model', { categoryId: 6, priority: 6 }],
  ['science', { categoryId: 6, priority: 6 }],
  ['culture', { categoryId: 9, priority: 6 }],
  ['awards', { categoryId: 9, priority: 6 }],
  ['rewards', { categoryId: 9, priority: 6 }],
  ['nobel', { categoryId: 9, priority: 6 }],
  ['prize', { categoryId: 9, priority: 6 }],
  ['gta vi', { categoryId: 9, priority: 6 }],
  ['declassification', { categoryId: 9, priority: 6 }],
  ['aliens', { categoryId: 9, priority: 6 }],
  ['breaking news', { categoryId: 2, priority: 5 }],
  ['featured', { categoryId: 2, priority: 5 }],
  ['all-in', { categoryId: 9, priority: 5 }],
  ['creators', { categoryId: 9, priority: 5 }],
  ['politics', { categoryId: 1, priority: 4 }],
  ['macro election 1', { categoryId: 1, priority: 4 }],
  ['macro election 2', { categoryId: 1, priority: 4 }],
  ['macro geopolitics', { categoryId: 2, priority: 4 }],
  ['all', { categoryId: 2, priority: 3 }],
  ['2025 predictions', { categoryId: 2, priority: 2 }],
  // Noisy tags like 'all' are omitted
]);

export function mapTagsToCategory(tags: string[]): CategoryId {
  let bestMatch: { categoryId: CategoryId; priority: number } = { categoryId: 2, priority: 0 }; // Default to Geopolitics

  for (const tag of tags) {
    const cleanTag = tag.toLowerCase().trim();
    const match = keywordMap.get(cleanTag);

    if (match && match.priority > bestMatch.priority) {
      bestMatch = match;
    }
  }

  return bestMatch.categoryId;
} 