// Define your categories
import { Category } from '@/lib/generated/prisma'
export const CATEGORIES = {
  1: 'Elections',
  2: 'Geopolitics & World Affairs',
  3: 'Economy & Economic Indicators',
  4: 'Financial Markets',
  5: 'Cryptocurrency',
  6: 'Science & Technology',
  7: 'Business & Corporate',
  8: 'Sports',
  9: 'Culture & Entertainment',
  10: 'Climate & Environment',
};

type CategoryId = keyof typeof CATEGORIES;

// Human-readable display names keyed by enum
export const CATEGORY_DISPLAY_NAME: Record<Category, string> = {
  [Category.ELECTIONS]: 'Elections',
  [Category.GEOPOLITICS]: 'Geopolitics & World Affairs',
  [Category.ECONOMY]: 'Economy & Economic Indicators',
  [Category.FINANCIAL_MARKETS]: 'Financial Markets',
  [Category.CRYPTOCURRENCY]: 'Cryptocurrency',
  [Category.SCIENCE_TECHNOLOGY]: 'Science & Technology',
  [Category.BUSINESS]: 'Business & Corporate',
  [Category.SPORTS]: 'Sports',
  [Category.CULTURE_ENTERTAINMENT]: 'Culture & Entertainment',
  [Category.CLIMATE_ENVIRONMENT]: 'Climate & Environment',
  [Category.OTHER]: 'Other',
};

// Keyword mapping uses enum values directly

// Keyword mapping with priorities (higher number = more important)
const keywordMap: Map<string, { category: Category; priority: number }> = new Map([
  // High Priority (Specific Identifiers)
  ['sports', { category: Category.SPORTS, priority: 10 }],
  ['formula 1', { category: Category.SPORTS, priority: 10 }],
  ['f1', { category: Category.SPORTS, priority: 10 }],
  ['mlb', { category: Category.SPORTS, priority: 10 }],
  ['nfl', { category: Category.SPORTS, priority: 10 }],
  ['soccer', { category: Category.SPORTS, priority: 10 }],
  ['baseball', { category: Category.SPORTS, priority: 10 }],
  ['crypto', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['bitcoin', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['btc', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['ethereum', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['eth', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['doge', { category: Category.CRYPTOCURRENCY, priority: 10 }],
  ['ai', { category: Category.SCIENCE_TECHNOLOGY, priority: 9 }],
  ['openai', { category: Category.SCIENCE_TECHNOLOGY, priority: 9 }],
  ['sam altman', { category: Category.SCIENCE_TECHNOLOGY, priority: 9 }],
  ['deepseek', { category: Category.SCIENCE_TECHNOLOGY, priority: 9 }],
  ['grok', { category: Category.SCIENCE_TECHNOLOGY, priority: 9 }],
  ['fed', { category: Category.ECONOMY, priority: 8 }],
  ['jerome powell', { category: Category.ECONOMY, priority: 8 }],
  ['powell', { category: Category.ECONOMY, priority: 8 }],
  ['mayor', { category: Category.ELECTIONS, priority: 8 }],
  ['nyc', { category: Category.ELECTIONS, priority: 8 }],
  ['movies', { category: Category.CULTURE_ENTERTAINMENT, priority: 8 }],
  ['box office', { category: Category.CULTURE_ENTERTAINMENT, priority: 8 }],
  ['hollywood', { category: Category.CULTURE_ENTERTAINMENT, priority: 8 }],
  ['climate', { category: Category.CLIMATE_ENVIRONMENT, priority: 8 }],
  ['weather', { category: Category.CLIMATE_ENVIRONMENT, priority: 8 }],
  ['global warming', { category: Category.CLIMATE_ENVIRONMENT, priority: 8 }],
  ['ukraine', { category: Category.GEOPOLITICS, priority: 8 }],
  ['putin', { category: Category.GEOPOLITICS, priority: 8 }],
  ['russia', { category: Category.GEOPOLITICS, priority: 8 }],
  ['zelensky', { category: Category.GEOPOLITICS, priority: 8 }],
  ['iran', { category: Category.GEOPOLITICS, priority: 8 }],
  ['israel', { category: Category.GEOPOLITICS, priority: 8 }],
  ['khamenei', { category: Category.GEOPOLITICS, priority: 8 }],
  ['middle east', { category: Category.GEOPOLITICS, priority: 8 }],
  ['china', { category: Category.GEOPOLITICS, priority: 8 }],
  ['taiwan', { category: Category.GEOPOLITICS, priority: 8 }],
  ['gaza', { category: Category.GEOPOLITICS, priority: 8 }],
  ['saudi arabia', { category: Category.GEOPOLITICS, priority: 8 }],
  ['kupyansk', { category: Category.GEOPOLITICS, priority: 8 }],
  ['atomic', { category: Category.GEOPOLITICS, priority: 8 }],
  ['bomb', { category: Category.GEOPOLITICS, priority: 8 }],
  ['nuclear', { category: Category.GEOPOLITICS, priority: 8 }],
  ['trump', { category: Category.ELECTIONS, priority: 8 }],
  ['maga', { category: Category.ELECTIONS, priority: 8 }],
  ['trump presidency', { category: Category.ELECTIONS, priority: 8 }],
  ['u.s. politics', { category: Category.ELECTIONS, priority: 8 }],
  ['congress', { category: Category.ELECTIONS, priority: 8 }],
  ['house', { category: Category.ELECTIONS, priority: 8 }],
  ['immigration', { category: Category.ELECTIONS, priority: 8 }],
  ['immigration/border', { category: Category.ELECTIONS, priority: 8 }],
  ['cabinet', { category: Category.ELECTIONS, priority: 8 }],
  ['epstein', { category: Category.ELECTIONS, priority: 8 }],
  ['trump vs elon', { category: Category.ELECTIONS, priority: 8 }],
  ['robert f. kennedy jr.', { category: Category.ELECTIONS, priority: 8 }],
  ['elon musk', { category: Category.ELECTIONS, priority: 8 }],
  ['world elections', { category: Category.ELECTIONS, priority: 8 }],
  ['global elections', { category: Category.ELECTIONS, priority: 8 }],
  ['elections', { category: Category.ELECTIONS, priority: 8 }],
  ['dutch', { category: Category.ELECTIONS, priority: 8 }],
  ['netherlands', { category: Category.ELECTIONS, priority: 8 }],
  ['chile', { category: Category.ELECTIONS, priority: 8 }],
  ['ireland', { category: Category.ELECTIONS, priority: 8 }],
  ['romania', { category: Category.ELECTIONS, priority: 8 }],
  ['south korea', { category: Category.ELECTIONS, priority: 8 }],
  ['javier milei', { category: Category.ELECTIONS, priority: 8 }],
  ['yoon', { category: Category.ELECTIONS, priority: 8 }],
  ['czechia', { category: Category.ELECTIONS, priority: 8 }],
  ['denmark', { category: Category.GEOPOLITICS, priority: 7 }],
  ['greenland', { category: Category.GEOPOLITICS, priority: 7 }],
  ['foreign policy', { category: Category.GEOPOLITICS, priority: 7 }],
  ['geopolitics', { category: Category.GEOPOLITICS, priority: 7 }],
  ['world', { category: Category.GEOPOLITICS, priority: 7 }],
  ['world affairs', { category: Category.GEOPOLITICS, priority: 7 }],
  ['us-iran', { category: Category.GEOPOLITICS, priority: 7 }],
  ['economic policy', { category: Category.ECONOMY, priority: 7 }],
  ['economy', { category: Category.ECONOMY, priority: 7 }],
  ['fed rates', { category: Category.ECONOMY, priority: 7 }],
  ['macro graph', { category: Category.ECONOMY, priority: 7 }],
  ['xtrd-1', { category: Category.ECONOMY, priority: 7 }],
  ['trade war', { category: Category.ECONOMY, priority: 7 }],
  ['treasuries', { category: Category.ECONOMY, priority: 7 }],
  ['balance', { category: Category.ECONOMY, priority: 7 }],
  ['budget', { category: Category.ECONOMY, priority: 7 }],
  ['deficit', { category: Category.ECONOMY, priority: 7 }],
  ['funding', { category: Category.ECONOMY, priority: 7 }],
  ['business', { category: Category.BUSINESS, priority: 6 }],
  ['big tech', { category: Category.BUSINESS, priority: 6 }],
  ['crypto prices', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['hit price', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['monthly', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['crypto policy', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['crypto summit', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['airdrops', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['pre-market', { category: Category.CRYPTOCURRENCY, priority: 6 }],
  ['finance', { category: Category.FINANCIAL_MARKETS, priority: 6 }],
  ['tech', { category: Category.SCIENCE_TECHNOLOGY, priority: 6 }],
  ['top model', { category: Category.SCIENCE_TECHNOLOGY, priority: 6 }],
  ['science', { category: Category.SCIENCE_TECHNOLOGY, priority: 6 }],
  ['culture', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['awards', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['rewards', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['nobel', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['prize', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['gta vi', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['declassification', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['aliens', { category: Category.CULTURE_ENTERTAINMENT, priority: 6 }],
  ['breaking news', { category: Category.GEOPOLITICS, priority: 5 }],
  ['featured', { category: Category.GEOPOLITICS, priority: 5 }],
  ['all-in', { category: Category.CULTURE_ENTERTAINMENT, priority: 5 }],
  ['creators', { category: Category.CULTURE_ENTERTAINMENT, priority: 5 }],
  ['politics', { category: Category.ELECTIONS, priority: 4 }],
  ['macro election 1', { category: Category.ELECTIONS, priority: 4 }],
  ['macro election 2', { category: Category.ELECTIONS, priority: 4 }],
  ['macro geopolitics', { category: Category.GEOPOLITICS, priority: 4 }],
  ['all', { category: Category.GEOPOLITICS, priority: 3 }],
  ['2025 predictions', { category: Category.GEOPOLITICS, priority: 2 }],
]);

export function mapTagsToCategory(tags: string[]): Category {
  let bestMatch: { category: Category; priority: number } = { category: Category.OTHER, priority: 0 };

  for (const tag of tags) {
    const cleanTag = tag.toLowerCase().trim();
    const match = keywordMap.get(cleanTag);

    if (match && match.priority > bestMatch.priority) {
      bestMatch = match;
    }
  }

  return bestMatch.category ?? Category.OTHER;
} 